In [ ]:
import os
os.environ["HF_HOME"] = "E:/huggingface"
#import transformers
from datasets import load_dataset

dataset = load_dataset("squad_it", trust_remote_code=True)
DEVICE = "cuda:0"

In [ ]:
from get_model import get_model
model_name = "gemma"

model, tokenizer = get_model(model_name)
#model = model.to(DEVICE) #togliere se in 4 bit

In [ ]:
from get_prompt import get_prompt
# del generate_prompt
generate_prompt, stop = get_prompt(model_name) #stop sembra useless

In [ ]:
def build_question(context, question):
    return f"Dato il seguente testo:\n{context}\nRispondi brevemente a questa domanda:\n{question}"

def build_answer(answer):
    return f"Risposta breve: {answer}"

In [ ]:
## test per gemma
def build_question(context, question):
    return f"contesto:\n{context}\ndomanda:\n{question}"

def build_answer(answer):
    return f"risposta: {answer}"

In [ ]:
import random

def get_shots(dataset, n):
    conversation = []
    for i in range(n):
        elem = random.choice(dataset["train"])
        q_shot = build_question(elem["context"], elem["question"])
        conversation.append(dict(
            role="user",
            text=q_shot
        ))
        conversation.append(dict(
            role="assistant",
            text=build_answer(elem["answers"]["text"][0])
        ))
    return conversation

In [ ]:
chat = [
  #{"role": "system", "content": "Sei un assistente utile." },
  {"role": "user", "content": "Ciao come va amico?" },
  {"role": "assistant", "content": "Tutto bene grazie." },
  {"role": "user", "content": "E tua sorella Alice?" },
  {"role": "assistant", "content": "è morta"},
  {"role": "user", "content": "Ah cavolo, mi dispiace."},
  {"role": "assistant", "content": "tranqui bro, è la vita"},
  {"role": "user", "content": "scusa come si chiama tua sorella?"},
] 
print(tokenizer.apply_chat_template(chat, tokenize=False))

In [23]:
import torch

def forward_model(*, prompt, model, tokenizer):

    if "pad_token" not in tokenizer.special_tokens_map:
        tokenizer.pad_token = tokenizer.eos_token

    input_ids = tokenizer(
        prompt,
        return_tensors='pt',
        padding=True,
    ).input_ids
    with torch.no_grad():
        input_ids = input_ids.to(DEVICE)
        output_ids = model.generate(
            input_ids=input_ids,
            max_new_tokens=32,
            temperature=0.001,
            repetition_penalty=1.2,
            eos_token_id=107,
            do_sample=True,
            num_return_sequences=1
        )
        print(output_ids)

    ret = []
    for i in range(0, len(output_ids)):
        generated_text = tokenizer.decode(
            output_ids[i],
            skip_special_tokens=True
        )
        # print(generated_text)
        # print(generated_text[len(prompt[i]):])
        generated_text = generated_text[len(prompt[i]):] #perchè in output_ids c'è anche il prompt!

        # if "\n" in generated_text:
        #     generated_text = generated_text[:generated_text.index("\n")] non necessario
        
        ret.append(generated_text.strip())

    return ret

In [24]:
import time

t0 = time.time()
out = forward_model(
    prompt=["contesto: Io lavoro a Londra. domanda: Dove lavoro? risposta:"],
    model=model,
    tokenizer=tokenizer,
)
print(time.time() - t0)

print(out)

tensor([[     2,   1739,  18470, 235292,  27266,  35212,    476, 134574, 235265,
          95962, 235292,  70274,  35212, 235336,  76742, 235292,    586, 134574,
         235265, 235248,    107]], device='cuda:0')
0.7209978103637695
['A Londra.']


In [21]:
### CELLA DI PROVA DEL NUOVO GET PROMPT DI SAIGA-ITA-7B!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!
import uuid
from tqdm import tqdm

batch_size = 1

predicted_answers = []
theoretical_answers = []

ds = dataset["test"].shuffle(seed=42)

total = 0
for i in range(3):
    elem     = ds[i].copy()
    ids      = elem["id"]
    context  = elem["context"]
    question = elem["question"]
    answers  = elem["answers"]

    model_inputs = []
    chat = get_shots(dataset, 3) + [
                dict(
                    role="user",
                    text=build_question(context, question)
                )
            ]
    model_inputs.append(
        generate_prompt(
        # scrive tre esempi non come  prompt ma come cronologia di chat: role: user -> text: domanda, role: assistant -> text: risposta breve
            chat,
            do_continue=False,
        ) + "" + build_answer("").strip()
    )

print(model_inputs[0])

<bos><start_of_turn>user
Di seguito ti verrà fornito un contesto e poi una domanda. il tuo compito è quello di rispondere alla domanda basandoti esclusivamente sul contesto.
contesto:
Napoleone sposò Joséphine de Beauharnais nel 1796, quando aveva 26 anni; era una vedova di 32 anni il cui primo marito era stato giustiziato durante la Rivoluzione. Fino a quando non incontrò Bonaparte, era stata conosciuta come "Rosa", un nome che non gli piaceva. La chiamò invece "Joséphine", e d' ora in poi andò con questo nome. Bonaparte spesso inviato le sue lettere d' amore durante le sue campagne. Ha formalmente adottato suo figlio Eugène e suo cugino Stéphanie e ha organizzato matrimoni dinastici per loro. Joséphine fece sposare la figlia Hortense con il fratello di Napoleone Louis.
domanda:
Chi ha sposato Napoleone nel 1796?
risposta: Joséphine de Beauharnais<end_of_turn>
<start_of_turn>contesto:
La popolarità del mandolino negli Stati Uniti è stata stimolata dal successo di un gruppo di giovani 

In [25]:
import uuid
from tqdm import tqdm

batch_size = 1

predicted_answers = []
theoretical_answers = []

ds = dataset["test"].shuffle(seed=42)
max_len = len(ds)


bar = tqdm(ds.iter(batch_size=batch_size), total=len(ds))
total = 0
for elem in bar:
    try:
        ids = elem["id"]
        context = elem["context"]
        question = elem["question"]
        answers = elem["answers"]

        model_inputs = []
        for c, q in zip(context, question):
            model_inputs.append(
                generate_prompt(
                    get_shots(dataset, 3) + [
                        dict(
                            role="user",
                            text=build_question(c, q)
                        )
                    ],
                    do_continue=False
                ) + " " + build_answer("").strip()
            )
        #print(model_inputs[0])
        # break

        model_outputs = forward_model(
            prompt=model_inputs[0],
            model=model,
            tokenizer=tokenizer,
        )
        
        model_outputs = model_outputs[0].split("Risposta breve:")[-1] if "Risposta breve:" in model_outputs[0] else _
        print(f"DOMANDA:\n{model_inputs[0]}\n\nRISPOSTA\n{model_outputs}\nSOLUZIONE\n{answers[0]['text']}\n")#[520:]



        # for model_output, id in zip(model_outputs, ids):
        #     predicted_answers.append(dict(
        #         id=id,
        #         prediction_text=model_output,
        #     ))
        predicted_answers.append(dict(
                id=ids[0],
                prediction_text=model_outputs,
            ))

        for ans, id in zip(answers, ids):
            theoretical_answers.append(dict(
                id=id,
                answers=ans,
            ))
        
    except Exception as e:
        print(e)
        continue

  0%|          | 1/7609 [00:01<2:43:19,  1.29s/it]

tensor([[     2,      2,    106,   1645,    108,   5523,  60520,    959, 125021,
         222809,    748, 153202,    526,  24702,   1749,  95962, 235265,   1800,
          28973, 200511,   4039,  29398,    751, 186479,   8097,  95962,   2572,
           2023,    487, 206214,   7809, 153202, 235265,    108,   1739,  18470,
         235292,    108, 235301, 235303,  43445, 235269,    683,  28551, 235269,
            683,  89320, 235269,   1800,   2399, 235704, 235269,   1800,  66823,
            526,    533, 235303,  43445,   8628,  47511,    496,  85104, 128431,
            751,  16706,  29219,   1177,  14451,  88892,    842,   9173,  19202,
          43896,   2590,   2287,  13113, 116261,    751,   1622,   3459,   3922,
           7249, 235248, 235284, 235276, 235274, 235304, 235289,    683, 111025,
         122240, 235269,    683,  48732,    534,   1820, 235269,  52676, 235269,
          66280,    526, 106484,  23758,  42804,  19543, 235289,    637, 203016,
         235269,  28076,    

  0%|          | 2/7609 [00:02<2:26:35,  1.16s/it]

tensor([[     2,      2,    106,   1645,    108,   5523,  60520,    959, 125021,
         222809,    748, 153202,    526,  24702,   1749,  95962, 235265,   1800,
          28973, 200511,   4039,  29398,    751, 186479,   8097,  95962,   2572,
           2023,    487, 206214,   7809, 153202, 235265,    108,   1739,  18470,
         235292,    108,   2841,  28551,    661,   6316,   1817,  42933,  17753,
           7249, 235248, 235274, 235315, 235308, 235304, 235265,  16575, 235248,
         235274, 235315, 235308, 235318, 235269,   1419, 143815,  46728, 235782,
          17909, 235269,  25496, 235703,    476,   6316,    895,    683,   4094,
          13322,    576,  59856,  12947,    578,  15171,  12720,    751, 137186,
           1800,  27743,  22906,   4748,  44636,  38403,  33995, 235265,  17753,
         235269,    526, 119814,  90152,   1234,  66684, 235782,   1800,  27743,
            751,   3402, 102250,   2063,  54951,   4748,   7467,  21405, 132637,
         235265,  16575, 235

  0%|          | 3/7609 [00:04<3:38:32,  1.72s/it]

tensor([[     2,      2,    106,  ..., 235265, 235248,    107]],
       device='cuda:0')
DOMANDA:
<bos><start_of_turn>user
Di seguito ti verrà fornito un contesto e poi una domanda. il tuo compito è quello di rispondere alla domanda basandoti esclusivamente sul contesto.
contesto:
Domesticamente, Barcellona ha vinto 23 La Liga, 27 Copa del Rey, 11 Supercopa de España, 3 Copa Eva Duarte e 2 trofei Copa de la Liga, oltre ad essere il detentore del record per le ultime quattro competizioni. Nel calcio di club internazionale, il Barcellona ha vinto cinque titoli UEFA Champions League, un record di quattro Coppa dei vincitori della Coppa UEFA, un record condiviso di cinque Supercoppa UEFA, un record di tre Coppa delle Fiere Inter-Cities e un record di tre trofei FIFA Club World Cup. Barcellona è stata classificata al primo posto nella classifica mondiale IFFHS Club World Ranking per il 1997,2009,2011,2012 e 2015 e attualmente occupa la seconda posizione nella classifica UEFA dei club. Il cl

  0%|          | 4/7609 [00:05<3:01:47,  1.43s/it]

tensor([[     2,      2,    106,  ..., 235304, 235248,    107]],
       device='cuda:0')
DOMANDA:
<bos><start_of_turn>user
Di seguito ti verrà fornito un contesto e poi una domanda. il tuo compito è quello di rispondere alla domanda basandoti esclusivamente sul contesto.
contesto:
A partire dal 1236, al principe mongolo Kublai (che in seguito governò come Khagan dal 1260–1294) fu concesso un grande appannaggio nella Cina del nord dal suo superiore Ögedei Khan. Karma Pakshi (1203–1283) — capo dei lama e secondo Karmapa della tradizione tibetana Karma Kagyu — rifiutò l'invito di Kublai di comparire nella sua corte, così Kublai invitò invece Drogön Chögyal Phagpa (1235–1280), successore e nipote di Sakya Pandita, che giunse nella sua corte nel 1253. Kublai istituì una peculiare relazione con il Phagpa lama, che riconosceva Kublai come un sovrano superiore negli affari politici e il Phagpa lama come il consigliere anziano di Kublai negli affari religiosi. Kublai nominò anche Drogön Chögyal

  0%|          | 5/7609 [00:08<4:06:25,  1.94s/it]

tensor([[     2,      2,    106,   1645,    108,   5523,  60520,    959, 125021,
         222809,    748, 153202,    526,  24702,   1749,  95962, 235265,   1800,
          28973, 200511,   4039,  29398,    751, 186479,   8097,  95962,   2572,
           2023,    487, 206214,   7809, 153202, 235265,    108,   1739,  18470,
         235292,    108,   6870,  82263,   4039,    748,  14341, 222991, 103033,
          12183,  24858, 235303,  29333, 235265,   2221, 103258,    661,    683,
           8189,   8223,  99859,   7987,   6886, 145707,   1531,   4039,    748,
          14341,  37404,  12230, 114993, 235265,   2221, 103258,   4039,  37256,
           1800,  73424,  37404,  12230,  55264,  19875,    575,  93051,   7249,
         235248, 235284, 235276, 235274, 235304, 235269,    683, 137200,    575,
          55863, 235269,    683,  12720,   2521,    575,  45358,    526,  61227,
            526,   1800,   8189,  14341,   9670,  91120,    526,   1800,   8189,
           8223,  37404,  12

  0%|          | 6/7609 [00:09<3:14:03,  1.53s/it]

tensor([[     2,      2,    106,  ...,  39750, 235248,    107]],
       device='cuda:0')
DOMANDA:
<bos><start_of_turn>user
Di seguito ti verrà fornito un contesto e poi una domanda. il tuo compito è quello di rispondere alla domanda basandoti esclusivamente sul contesto.
contesto:
Oltre ai ristoranti classici, Parigi ha molti altri tipi di ristoranti tradizionali. Il caffè è arrivato a Parigi nel XVII secolo, quando la bevanda è stata portata per la prima volta dalla Turchia, e dal XVIII secolo i caffè parigini erano centri della vita politica e culturale della città. Il Cafe Procope on the Left Bank risale a questo periodo. Nel XX secolo, i caffè della Left Bank, in particolare il Café de la Rotonde e il Le Dôme Café di Montparnasse e il Café de Flore e Les Deux Magots sul Boulevard Saint Germain, tutti ancora in attività, sono stati importanti luoghi d' incontro per pittori, scrittori e filosofi. Un bistrot è un tipo di ristorante definito liberamente come un ristorante di quartiere 

  0%|          | 7/7609 [00:10<2:44:11,  1.30s/it]

tensor([[     2,      2,    106,  ...,  74802, 235248,    107]],
       device='cuda:0')
DOMANDA:
<bos><start_of_turn>user
Di seguito ti verrà fornito un contesto e poi una domanda. il tuo compito è quello di rispondere alla domanda basandoti esclusivamente sul contesto.
contesto:
L' 11 agosto, Barcellona ha iniziato la stagione 2015-16 vincendo il quinto record europeo di Supercoppa europea vincendo la Sevilla FC 5-4 nella Supercoppa UEFA del 2015. Si sono conclusi l' anno con una vittoria di 3-0 sul club argentino River Plate nella finale della FIFA Club World Cup del 2015 il 20 dicembre per vincere il trofeo per la terza volta record, con Suárez, Messi e Iniesta i primi tre giocatori del torneo. La Coppa del Mondo di Club FIFA è stato il ventesimo titolo internazionale di Barcellona, un record solo eguagliato dal club egiziano Al Ahly SC. Con 180 gol nel 2015 in tutte le competizioni, Barcellona ha stabilito il record per la maggior parte dei gol segnati in un anno solare, rompendo 

  0%|          | 8/7609 [00:11<2:32:22,  1.20s/it]

tensor([[     2,      2,    106,  ..., 235358, 235248,    107]],
       device='cuda:0')
DOMANDA:
<bos><start_of_turn>user
Di seguito ti verrà fornito un contesto e poi una domanda. il tuo compito è quello di rispondere alla domanda basandoti esclusivamente sul contesto.
contesto:
P?? upatas ha diviso il mondo creato in insenzienti e senzienti. L' insenziente era l' inconscio e quindi dipendente dal senziente o cosciente. L' insenatura è stata ulteriormente divisa in effetti e cause. Gli effetti erano di dieci tipi, la terra, quattro elementi e le loro qualità, il colore ecc. Le cause erano di tredici tipi, i cinque organi della cognizione, i cinque organi d' azione, i tre organi interni, l' intelletto, il principio dell' ego e il principio della conoscenza. Queste cause insenzienti sono state ritenute responsabili dell' illusiva identificazione di sé con il non Sé. La salvezza in P? upata ha coinvolto l' unione dell' anima con Dio attraverso l' intelletto.
domanda:
Per le Pasupate, co

  0%|          | 9/7609 [00:13<3:34:57,  1.70s/it]

tensor([[   2,    2,  106,  ..., 6141, 2784, 3000]], device='cuda:0')
DOMANDA:
<bos><start_of_turn>user
Di seguito ti verrà fornito un contesto e poi una domanda. il tuo compito è quello di rispondere alla domanda basandoti esclusivamente sul contesto.
contesto:
Il processo di fondazione dell' università pubblica del paese iniziò l' 11 giugno 1833 con l' approvazione di una legge proposta dal senatore Dámaso Antonio Larrañaga. Ha chiesto la creazione di nove dipartimenti accademici; il Presidente della Repubblica adotterà un decreto che istituirà formalmente i dipartimenti una volta che la maggior parte di essi sarà operativa. Nel 1836 si formò la Casa di Studi Generali che ospitava i dipartimenti di latino, filosofia, matematica, teologia e giurisprudenza. Il 27 maggio 1838 Manuel Oribe emanò un decreto che istituiva la Grande Università della Repubblica. Tale decreto ha avuto pochi effetti pratici, data l' instabilità istituzionale della Repubblica Orientale dell' Uruguay in quel mom

  0%|          | 10/7609 [00:15<3:47:22,  1.80s/it]

tensor([[     2,      2,    106,  ...,  15378, 235248,    107]],
       device='cuda:0')
DOMANDA:
<bos><start_of_turn>user
Di seguito ti verrà fornito un contesto e poi una domanda. il tuo compito è quello di rispondere alla domanda basandoti esclusivamente sul contesto.
contesto:
Dal 1996 vi sono indicazioni che Everton si trasferirà in un nuovo stadio. Il progetto originale prevedeva la costruzione di un nuovo stadio da 60.000 posti a sedere, ma nel 2000 è stata presentata una proposta per la costruzione di uno stadio da 55.000 posti come parte della rigenerazione del King's Dock. Ciò non ha avuto successo in quanto Everton non è riuscita a generare i 30 milioni di sterline necessari per la metà della partecipazione al progetto dello stadio, e il consiglio comunale ha respinto la proposta nel 2003. Alla fine del 2004, guidato dal Liverpool Council e dalla Northwest Development Corporation, il club ha avviato colloqui con Liverpool F. C. sulla condivisione di uno stadio proposto su St

  0%|          | 11/7609 [00:16<3:13:11,  1.53s/it]

tensor([[     2,      2,    106,  ..., 235265, 235248,    107]],
       device='cuda:0')
DOMANDA:
<bos><start_of_turn>user
Di seguito ti verrà fornito un contesto e poi una domanda. il tuo compito è quello di rispondere alla domanda basandoti esclusivamente sul contesto.
contesto:
Investimenti nella città ha continuato. La William Enston Home, una comunità pianificata per gli anziani e gli infermi della città, fu costruita nel 1889. Nel 1896, nel cuore della città, il governo federale completò nel 1896 un complesso edificio pubblico, l' ufficio postale e tribunale degli Stati Uniti. La legislatura statale dominata dai Democratici approvò una nuova costituzione nel 1895 che disfranchise i neri, escludendoli completamente dal processo politico, uno status di seconda classe che fu mantenuto per più di sei decenni in uno stato che fino al 1930 circa era a maggioranza nera.
domanda:
La William Enston Home è stata costruita in quale anno?
risposta: 1889.<end_of_turn>
<start_of_turn>contesto

  0%|          | 12/7609 [00:17<2:53:50,  1.37s/it]

tensor([[     2,      2,    106,   1645,    108,   5523,  60520,    959, 125021,
         222809,    748, 153202,    526,  24702,   1749,  95962, 235265,   1800,
          28973, 200511,   4039,  29398,    751, 186479,   8097,  95962,   2572,
           2023,    487, 206214,   7809, 153202, 235265,    108,   1739,  18470,
         235292,    108,   2841,  35790,   4039,   8639,    784,   1260,    748,
         176197,    526,   1260,    748,  94611, 164014,    751, 235248, 235315,
         136854, 235265,  16575, 235248, 235284, 235276, 235276, 235318, 235269,
            683,   6878,    751,  54674,   4748,  35790,   4039,  21967,    784,
           1260,    748,  54674,  94611, 235290,  16914,  33222,    476,    748,
          54674,  25563, 176197, 235265,   4626, 202839,   4039,  20935,   4421,
           1817,   1260,    748,  76499,    575,  41814,    683,  35790,   7249,
         235248, 235284, 235276, 235276, 235310, 235265,   4626, 176197,   4039,
            575,  91223,    

  0%|          | 13/7609 [00:18<2:36:59,  1.24s/it]

tensor([[     2,      2,    106,   1645,    108,   5523,  60520,    959, 125021,
         222809,    748, 153202,    526,  24702,   1749,  95962, 235265,   1800,
          28973, 200511,   4039,  29398,    751, 186479,   8097,  95962,   2572,
           2023,    487, 206214,   7809, 153202, 235265,    108,   1739,  18470,
         235292,    108,  34400, 235248, 235274, 235321, 235315, 235308,   1800,
          37302,   6085,    639,   3000,   7373,  31867,  24007,    533, 235303,
           4268,  46170,   1177, 144450,  19520,    751,  51074,  62045, 235265,
          88232,    526,  26684, 235290,  71462, 232790,   6121,   8673,   4388,
            683,  12720, 106853,   4081,  80181, 235269,    476,  96471,   4068,
         235248, 235304, 235276,  57055, 235248, 235274, 235315, 235274, 235318,
         235265,   5213,  63136,  54126, 128431,    533, 235303,  22149, 130034,
            575,  72921,   7076,   6924, 235269,  67025,  25052,    683, 139864,
          37913,   4148,  18

  0%|          | 14/7609 [00:21<3:41:47,  1.75s/it]

tensor([[     2,      2,    106,  ..., 130034,    842,   3859]],
       device='cuda:0')
DOMANDA:
<bos><start_of_turn>user
Di seguito ti verrà fornito un contesto e poi una domanda. il tuo compito è quello di rispondere alla domanda basandoti esclusivamente sul contesto.
contesto:
La qualità di un vuoto è indicata dalla quantità di materia rimanente nel sistema, in modo che un vuoto di alta qualità è uno con molto poco materiale rimasto in esso. Il vuoto viene misurato principalmente dalla pressione assoluta, ma una caratterizzazione completa richiede ulteriori parametri, come la temperatura e la composizione chimica. Uno dei parametri più importanti è il percorso libero medio (MFP) dei gas residui, che indica la distanza media che le molecole percorreranno tra una collisione e l' altra. Quando la densità del gas diminuisce, il multifunzione aumenta e quando il multifunzione è più lungo della camera, della pompa, della navicella spaziale o di altri oggetti presenti, le ipotesi continuu

  0%|          | 15/7609 [00:23<3:29:53,  1.66s/it]

tensor([[     2,      2,    106,   1645,    108,   5523,  60520,    959, 125021,
         222809,    748, 153202,    526,  24702,   1749,  95962, 235265,   1800,
          28973, 200511,   4039,  29398,    751, 186479,   8097,  95962,   2572,
           2023,    487, 206214,   7809, 153202, 235265,    108,   1739,  18470,
         235292,    108,   2025, 175462,   1061,    506,   2784,  46328,  22149,
          76513,   1749,  82085,  39186,    575,  14852,   5783,    526,  54719,
          68650,  92103, 235269,    476, 107685,    895,  24815, 235303, 100620,
          34879,    751, 218752,  20580,    526, 231457,  25032, 235252, 235269,
           1265,  22149, 127209,    709,  28174,   3072,    551,    785,   2063,
         217793, 235265,  92878,    533, 235303,  43165,  18276,  12585,    543,
          22193,  25032, 235252, 235269,  31580,   2236,    526, 197633,  20580,
            751, 205968,    532,  60936,   1804,  56962,  86729,    493, 110924,
           5425,    550,    

  0%|          | 16/7609 [00:23<2:57:19,  1.40s/it]

tensor([[     2,      2,    106,  ...,  19395, 235248,    107]],
       device='cuda:0')
DOMANDA:
<bos><start_of_turn>user
Di seguito ti verrà fornito un contesto e poi una domanda. il tuo compito è quello di rispondere alla domanda basandoti esclusivamente sul contesto.
contesto:
Nel corso del XX secolo, la contea è diventata sempre più urbanizzata, in particolare nella parte meridionale. Ai comuni di contea esistenti di Barrow-in-Furness, Blackburn, Bolton, Bootle, Burnley, Burnley, Bury, Liverpool, Manchester, Oldham, Preston, Preston, Rochdale, Salford, St Helens e Wigan sono stati aggiunti Blackpool (1904), Southport (1905) e Warrington (1900). Anche i comuni della contea avevano molte estensioni dei confini. I confini intorno alla zona di Manchester erano particolarmente complicati, con le strette sporgenze della contea amministrativa tra i comuni della contea - quartiere urbano di Lees formato una parte distaccata della contea amministrativa, tra Oldham distretto contea e l' Equ

  0%|          | 17/7609 [00:25<3:13:32,  1.53s/it]

tensor([[     2,      2,    106,   1645,    108,   5523,  60520,    959, 125021,
         222809,    748, 153202,    526,  24702,   1749,  95962, 235265,   1800,
          28973, 200511,   4039,  29398,    751, 186479,   8097,  95962,   2572,
           2023,    487, 206214,   7809, 153202, 235265,    108,   1739,  18470,
         235292,    108,  17424,    646, 235265,   5978,   5854,    661,  65775,
          30431,  23758,  35688,  41558,    487,   1265, 235269,    699, 177664,
            683,   4510,  10038,   1006,  77443,    526,  77095,  16666,   1966,
          41894,  48326,    784,  13113,  70703,   4081,  18276,  68650,  92103,
         235269,  41182,   2173,  28773,   1265,   2173,    875,   4097,   1749,
         180336, 100990,  13113,  69877,  72619,  18276,  68650,  92103, 235265,
           5478,  36812,   1800,  57958,    664,  41615,   2671,  67528, 235281,
            842,   3859,   9139,    683, 107449, 216968,   1006,  72619,    526,
         190640,  54719,  68

  0%|          | 18/7609 [00:26<2:49:59,  1.34s/it]

tensor([[     2,      2,    106,   1645,    108,   5523,  60520,    959, 125021,
         222809,    748, 153202,    526,  24702,   1749,  95962, 235265,   1800,
          28973, 200511,   4039,  29398,    751, 186479,   8097,  95962,   2572,
           2023,    487, 206214,   7809, 153202, 235265,    108,   1739,  18470,
         235292,    108,   6870,   1142,  13207,   8022,    575,  11557,    751,
          60289, 235269,  11909,    576,   8186,    591, 235274, 235315, 235315,
         235321,    823,  36215,  19335,    852,    748, 202839,  13113,   7682,
          64435, 235265,   5478,  10642,   1817,    632,   1800, 222991,    751,
         137738,   1820,   7130,  97970,    526,    661, 148874,  91159,    748,
         168518,   1265,   2688,  11085,   6316,    654,  48762,  11877,    632,
           2463,    526,   7095, 148361,   2581, 235265,   4626,   2708,   5252,
          87637,  60334,   7600,  40855, 107660, 235782,   1265,  29398,   1265,
          60289,   2041, 235

  0%|          | 19/7609 [00:28<2:59:20,  1.42s/it]

tensor([[     2,      2,    106,   1645,    108,   5523,  60520,    959, 125021,
         222809,    748, 153202,    526,  24702,   1749,  95962, 235265,   1800,
          28973, 200511,   4039,  29398,    751, 186479,   8097,  95962,   2572,
           2023,    487, 206214,   7809, 153202, 235265,    108,   1739,  18470,
         235292,    108,   6870,  22906,    875,  41141,   2170,    748,  86457,
           7809, 166534,  58379,   1800,  17358, 100709,    751,  74173,  48936,
          10422,  19335, 235269,    718,   1800, 166534,  21829, 109537,    654,
            742,  71538,  74173,    591,    484,  66015,   1800,   4817,    539,
          75168,    664, 187883, 229441,   4764,   1388,    632,   1749,  47802,
          11671,    751,   3402,   1390,   3423,    575,  24200,   7467, 235265,
          42463,    709,   3402,   2270,   1177, 166534,   2173,  26160,  37348,
            476,  76346,    895,   1749,   1423,    751,  21818,  12696, 235269,
           1800,  22906,  21

  0%|          | 19/7609 [00:28<3:11:15,  1.51s/it]


KeyboardInterrupt: 

In [ ]:
import os
import json



# Create the directory if it doesn't exist
os.makedirs('./cache', exist_ok=True)
with open(f"./cache/generated-squad-{model_name}.json", "w") as f:
    json.dump(dict(
        predicted_answers=predicted_answers,
        theoretical_answers=theoretical_answers,
    ), f, indent=4)

In [ ]:
import json
with open(f"./cache/generated-squad-{model_name}.json", "r") as f:
    data = json.load(f)

print(len(data["predicted_answers"]))

In [ ]:
import evaluate

predicted_answers = data["predicted_answers"]
theoretical_answers = data["theoretical_answers"]

metric = evaluate.load("squad")
results = metric.compute(predictions=predicted_answers, references=theoretical_answers)

import time


print("=== REPORT ===")
print("current date:", time.strftime("%d/%m/%Y %H:%M:%S"))
print("Dataset: SQuAD-it")
print("Model:", model_name)
print(results)
print("==========================")